version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: _docker/php/Dockerfile
        container_name: obm_app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
        environment:
            - DB_HOST=mysql
            - DB_PORT=3306
            - DB_DATABASE=obm
            - DB_USERNAME=obm
            - DB_PASSWORD=obm
        networks:
            - laravel-network

    webserver:
        image: nginx:alpine
        container_name: obm_web
        restart: unless-stopped
        ports:
            - "9870:80"
        volumes:
            - ./:/var/www
            - ./_docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - laravel-network
        depends_on:
            - app

    mysql:
        image: mysql:8.0
        container_name: obm_db
        restart: unless-stopped
        environment:
            - MYSQL_DATABASE=obm
            - MYSQL_USER=obm
            - MYSQL_PASSWORD=obm
            - MYSQL_ROOT_PASSWORD=root
        volumes:
            - mysql-data:/var/lib/mysql
            - ./_docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
        ports:
            - "3306:3306"
        networks:
            - laravel-network

volumes:
    mysql-data:
        driver: local

networks:
    laravel-network:
        driver: bridge
